security:
    encoders:
        Acme\SmallstepsBundle\Entity\User: 
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Acme\SmallstepsBundle\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/            
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: default_security_target
                provider: main
                csrf_provider: form.csrf_provider
                remember_me: true
            logout: 
                path: /logout
                target: /login
                invalidate_session : false
            anonymous:    true                  
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER       
            
            

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgetPassword, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Parent/*, roles: ROLE_USER }
        - { path: ^/Admin/*, role: ROLE_ADMIN }
       
        