language: php

php:
  - 5.6

before_script: composer install -n

script: phpunit -c app
  - sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.login=$SONAR_TOKEN -X

addons:
  sonarqube: true

env:
  global:
  — secure: SecuredSonarToken
    - SONAR_HOST_URL=SonarHostURL
