Admin_Booking:
    path:     /
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:index" }

Admin_Booking_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:show" }

Admin_Booking_new:
    path:     /new
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:new" }

Admin_Booking_create:
    path:     /create
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:create" }
    requirements: { _method: post }

Admin_Booking_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:edit" }

Admin_Booking_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:update" }
    requirements: { _method: post|put }

Admin_Booking_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeSmallstepsBundle:Booking:delete" }
    requirements: { _method: post|delete }
