parameters:
#    acme_smallsteps.example.class: Acme\SmallstepsBundle\Example

services:
#    acme_smallsteps.example:
#        class: %acme_smallsteps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
