<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildRepository extends EntityRepository
{
    public function findAllByParentId($parent) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c FROM AcmeSmallstepsBundle:Child c WHERE c.parent = :parent'
                        )->setParameter('parent', $parent)
                        ->getResult();
    }
    
    public function getChildClass($dob){
        
        $dob = new DateTime($dob['dob']);
        $date = new DateTime(date('Y-m-d'));

        $age = $date->diff($dob);

        if ($age->y >= 0 && $age->y <= 2) {
            return 1;
        } else if ($age->y > 2 && $age->y <= 3) {
            return 2;
        } else if ($age->y >= 3 && $age->y <= 5) {
            return 3;
        } else{
            return 4;
        }
    
    }
}
