<?php

namespace Acme\SmallstepsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NurseryDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurseryDetailRepository extends EntityRepository
{
}
